title: Kiel Dang # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist / ML Engineer with 6+ years of commercial experience in analytics and strategy.
  Completed a Master's degree in Data Science from Northeastern University. 
  Previously at Definity, Northeastern University, Alibaba E-commerce, VINAMILK and Unilever Vietnam.
  <br><br>
  Ranked top 1 student of the faculty (Fall 2021 Cohort) and served as a Statistics TA at the university. 
  <br><br>
  <a href="https://www.linkedin.com/in/kirudang/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://medium.com/@kirudang">View My Medium Blog</a> 
  <br><br>
  <a href="https://github.com/kirudang">Return my Github</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
